// ---------- DOM References ----------
const chatForm = document.getElementById("chat-form");
const userInput = document.getElementById("user-input");
const chatBox = document.getElementById("chat-box");
const voiceBtn = document.getElementById("voice-btn");
const providerSelect = document.getElementById("provider-select");
const mobileMenuBtn = document.getElementById("mobile-menu-btn");
const sidebar = document.getElementById("sidebar");
const userAvatar = document.getElementById("user-avatar");
const userAvatarSidebar = document.getElementById("user-avatar-sidebar");
const welcomeScreen = document.getElementById("welcome-screen");

// New DOM references for the buttons
const newChatBtn = document.querySelector("#sidebar button:first-of-type");
const searchBtn = document.querySelector("#sidebar button:nth-of-type(2)");
const settingsBtn = document.querySelector("#sidebar .mt-auto button:first-of-type");

// ---------- Global Variables ----------
let currentUser = "guest";
let mediaRecorder,
  audioChunks = [];
let audio = new Audio();

// IMPORTANT: Get the backend URL from the global variable set in index.html
const backendBaseUrl = window.BACKEND_URL;

// ---------- Init ----------
function init() {
  const provider = localStorage.getItem("provider") || "openrouter";
  providerSelect.value = provider;
  updateUserAvatar(currentUser);
}

function updateUserAvatar(username) {
  if (userAvatar) {
    userAvatar.src = `https://ui-avatars.com/api/?name=${encodeURIComponent(
      username
    )}&background=22c55e&color=fff`;
  }
  if (userAvatarSidebar) {
    userAvatarSidebar.src = `https://ui-avatars.com/api/?name=${encodeURIComponent(
      username
    )}&background=22c55e&color=fff`;
  }
}

// ---------- Chat Message Submission ----------
chatForm.addEventListener("submit", async (e) => {
  e.preventDefault();
  const message = userInput.value.trim();
  if (!message) return;

  // Hide the welcome screen and show the chat box if it's the first message
  if (welcomeScreen.style.display !== "none") {
    welcomeScreen.style.display = "none";
    chatBox.classList.remove("hidden");
  }

  appendMessage("You", message, "user");
  userInput.value = "";

  const loader = appendMessage("Quainex", "...", "bot", true);
  showTyping(loader.querySelector(".typing"));

  try {
    const body = {
      message: message,
      provider: providerSelect.value,
      personality: "default",
    };

    const res = await fetch(`${backendBaseUrl}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });

    const data = await res.json();
    loader.remove();

    // Log provider to console for admin view only
    if (data.final_provider) {
      console.info(`💡 Response generated by: ${data.final_provider}`);
    }

    if (!res.ok || data.success === false) {
      const errMsg = data.error || `Error: ${res.status} ${res.statusText}`;
      console.error("Chat API error:", errMsg, data);
      appendMessage("Quainex", `⚠️ ${errMsg}`, "bot");
      return;
    }

    if (!data.response || !data.response.trim()) {
      console.warn("Empty AI response:", data);
      appendMessage("Quainex", "⚠️ I got an empty response. Please try again.", "bot");
      return;
    }

    appendMessage("Quainex", data.response, "bot");
  } catch (error) {
    console.error("Chat network error:", error);
    loader.remove();
    appendMessage("Quainex", "⚠️ Sorry, I encountered a network error. Please try again.", "bot");
  }
});

// ---------- Typing Dots Animation ----------
function showTyping(el) {
  let dots = 0;
  const interval = setInterval(() => {
    if (!el || !el.isConnected) {
      clearInterval(interval);
      return;
    }
    el.textContent = ".".repeat((dots++ % 4));
  }, 300);
}

// ---------- Append Message to Chat ----------
function appendMessage(sender, text, type = "bot", loading = false) {
  const wrapper = document.createElement("div");
  wrapper.className = `flex ${type === "user" ? "justify-end" : "justify-start"} fade-in`;
  
  const bubble = document.createElement("div");
  bubble.className = `px-5 py-3 rounded-2xl shadow max-w-[90%] md:max-w-[80%] whitespace-pre-wrap ${
    type === "user"
      ? "bg-primary-600 text-white rounded-br-none user-bubble"
      : "bg-dark-700 text-white rounded-bl-none bot-bubble"
  }`;
  
  const senderElement = document.createElement("div");
  senderElement.className = `text-xs font-semibold mb-1 ${
    type === "user" ? "text-primary-200" : "text-gray-400"
  }`;
  senderElement.textContent = sender;
  bubble.appendChild(senderElement);

  if (loading) {
    const typing = document.createElement("span");
    typing.classList.add("typing");
    typing.textContent = "...";
    bubble.appendChild(typing);
  } else {
    const contentElement = document.createElement("div");
    contentElement.className = "text-gray-100";
    contentElement.textContent = text;
    bubble.appendChild(contentElement);
  }

  wrapper.appendChild(bubble);
  chatBox.appendChild(wrapper);
  chatBox.scrollTop = chatBox.scrollHeight;
  return wrapper;
}

// ---------- Voice Input ----------
voiceBtn.addEventListener("click", async () => {
  if (mediaRecorder && mediaRecorder.state === "recording") {
    mediaRecorder.stop();
    voiceBtn.classList.remove("text-red-500");
    voiceBtn.classList.add("text-gray-400");
    return;
  }
  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    mediaRecorder = new MediaRecorder(stream);
    audioChunks = [];
    mediaRecorder.ondataavailable = (e) => audioChunks.push(e.data);
    mediaRecorder.onstop = async () => {
      const audioBlob = new Blob(audioChunks, { type: "audio/webm" });
      const formData = new FormData();
      formData.append("file", audioBlob);
      const loader = appendMessage("Quainex", "Transcribing voice...", "bot", true);
      try {
        const res = await fetch(`${backendBaseUrl}/voice`, { method: "POST", body: formData });
        const data = await res.json();
        loader.remove();
        appendMessage("Quainex", data.response, "bot");
      } catch (error) {
        console.error("Voice transcription error:", error);
        loader.remove();
        appendMessage("Quainex", "⚠️ Voice transcription failed. Please try again.", "bot");
      }
    };
    mediaRecorder.start();
    voiceBtn.classList.remove("text-gray-400");
    voiceBtn.classList.add("text-red-500");
    showCustomMessage("Recording... Click again to stop");
  } catch (error) {
    console.error("Error accessing microphone:", error);
    showCustomMessage("Microphone access denied: " + error.message);
  }
});

// ---------- Sidebar Actions (New!) ----------
// New Chat
newChatBtn.addEventListener("click", () => {
  chatBox.innerHTML = ""; // Clear all messages
  chatBox.classList.add("hidden"); // Hide the chat box
  welcomeScreen.style.display = "block"; // Show the welcome screen
  sidebar.classList.remove("active"); // Hide the sidebar
  overlay.classList.remove("active"); // Hide the overlay
  showCustomMessage("Started a new chat!");
});

// Search
searchBtn.addEventListener("click", () => {
  showCustomMessage("Search functionality not implemented yet.");
  sidebar.classList.remove("active");
  overlay.classList.remove("active");
});

// Settings
settingsBtn.addEventListener("click", () => {
  showCustomMessage("Settings page not implemented yet.");
  sidebar.classList.remove("active");
  overlay.classList.remove("active");
});

// ---------- Sidebar Toggle ----------
const overlay = document.getElementById("overlay");
mobileMenuBtn.addEventListener("click", () => {
  sidebar.classList.toggle("active");
  overlay.classList.toggle("active");
});
overlay.addEventListener("click", () => {
  sidebar.classList.remove("active");
  overlay.classList.remove("active");
});

// ---------- Provider Change ----------
providerSelect.addEventListener("change", () => {
  localStorage.setItem("provider", providerSelect.value);
  showCustomMessage(`Model provider set to ${providerSelect.options[providerSelect.selectedIndex].text}`);
});

// ---------- Custom Message Display ----------
function showCustomMessage(message) {
  const messageDiv = document.createElement("div");
  messageDiv.className = "fixed top-4 right-4 bg-primary-600 text-white px-4 py-2 rounded-lg shadow-lg z-[1000] flex items-center space-x-2 fade-in";
  const icon = document.createElement("i");
  icon.className = "fas fa-info-circle";
  messageDiv.appendChild(icon);
  const text = document.createElement("span");
  text.textContent = message;
  messageDiv.appendChild(text);
  document.body.appendChild(messageDiv);
  setTimeout(() => {
    messageDiv.classList.add("opacity-0", "translate-y-2");
    setTimeout(() => {
      messageDiv.remove();
    }, 300);
  }, 3000);
}

// ---------- Run Init ----------
init();